# Generated by Django 5.2.1 on 2025-05-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_orderdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
